source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-sitemap", "~> 1.4"
gem "bundler", ">= 1.16"
gem "rake", "~> 12.0"
gem "kramdown-parser-gfm"
gem "jekyll-seo-tag"
gem "jekyll-redirect-from"